filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key:
  tags: ["nginx"]

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi/*
  json:
    keys_under_root: true
    add_error_key: true
  tags: ["fastapi"]

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi_auth/*
  json:
    keys_under_root: true
    add_error_key:
  tags: ["fastapi_auth"]

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi_ugc/*
  json:
    keys_under_root: true
    add_error_key:
  tags: ["fastapi_ugc"]

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi_ws/*
  json:
    keys_under_root: true
    add_error_key:
  tags: ["fastapi_ws"]

- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi_recom/*
  json:
    keys_under_root: true
    add_error_key:
  tags: ["fastapi_recom"]

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_DSN}"]
