name: Type check with mypy

on:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-protobuf

    - name: Run mypy
      run: |
        mypy --explicit-package-bases \
          --disable-error-code=union-attr \
          --disable-error-code=import-untyped \
          --disable-error-code=valid-type \
          --disable-error-code=assignment \
          --disable-error-code=attr-defined \
          --disable-error-code=index \
          --disable-error-code=annotation-unchecked \
